sudo: required
services:
  - docker

before_install:
  - docker build -t pensive_kowalevski/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true pensive_kowalevski/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: 'us-east-2'
  app: 'docker-react'
  env: 'Docker-env'
  bucket_name: 'elasticbeanstalk-us-east-2-985364952418'
  bucket_path: 'docker-react'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: '$AWS_SECRET_KEY'
